### ISSUE TITLE
Error：请确认调用规则是否正确

### ISSUE THREAD

**Issue by x64bugreport** [WPeace-HcH/SysNR-FuncFinder#2]
[DEMO.zip](https://github.com/WPeace-HcH/SysNR-FuncFinder/files/10267090/DEMO.zip)
1.可否支持一下arm64?
2.我认为此处匹配不严谨op = re.findall('(?<=0x9).*$', op);，建议匹配到SVC后通过IDAAPI遍历汇编上下文处理
3.有部分混淆的so，ida无法识别成函数，使用函数遍历的方式可能会错过某些SVC，希望考虑以下场景。

**Comment by WPeace-HcH** [comment]
感谢 Issue : )
1. 身体转阴后将会把插件支持arm64。
2. 暂不考虑 so 文件，之后如果有大量需求再考虑修改。
