### ISSUE TITLE
当前插件仅支持EXEC可执行ELF文件。

### ISSUE THREAD

**Issue by XKaguya** [WPeace-HcH/SysNR-FuncFinder#5]
报错：
SysNR-FuncFinder v2.2 start running...
当前插件仅支持EXEC可执行ELF文件。

不知道为什么，我手上的ELF文件全都是这样，就算修改后缀名为ELF也不能使用插件
不清楚是BUG还是我的操作问题，因为我看issue里面只有我是这样的

**Comment by WPeace-HcH** [comment]
你好，可以将其中某一个ELF文件通过邮箱发给我看看，这个报错一般是因为解析ELF文件格式发现并不是可执行文件。

**Comment by XKaguya** [comment]
> 你好，可以将其中某一个ELF文件通过邮箱发给我看看，这个报错一般是因为解析ELF文件格式发现并不是可执行文件。

好的，已发送

**Comment by WPeace-HcH** [comment]
你好，我查看了收到的附件文件，插件当前主要支持的是 ET_EXEC 可执行文件，暂不支持共享对象文件。
可以查看 testSamples 文件夹中的示例样本试用插件了解适用范围。 : )

**Comment by XKaguya** [comment]
> 你好，我查看了收到的附件文件，插件当前主要支持的是 ET_EXEC 可执行文件，暂不支持共享对象文件。 可以查看 testSamples 文件夹中的示例样本试用插件了解适用范围。 : )

好的，谢谢
是必须要头部信息里`  Type:                              EXEC (Executable file)`
这样的是吧

**Comment by WPeace-HcH** [comment]
是的
