### ISSUE TITLE
MIPS 32位系统调用号恢复错误。

### ISSUE THREAD

**Issue by badboycxcc** [WPeace-HcH/SysNR-FuncFinder#6]
syscall 4142 程序恢复为：newselect，实际应该为pipe
参考地址：https://syscalls.w3challs.com/?arch=mips_o32

**Comment by WPeace-HcH** [comment]
查看对应链接中 4142 对应函数就是 _newselect ...

**Comment by badboycxcc** [comment]
不好意思，看样本看晕了。
